trigger: none  # Se ejecuta manualmente o programado

stages:
  - stage: Deploy_Microservices
    jobs:
      - job: Trigger_Microservices
        steps:
          - checkout: none
          - task: AzurePipelinesRunPipeline@1
            displayName: "Ejecutar Pipeline de Microservicios"
            inputs:
              definition: "deploy-microservices"
              parameters: "{}"

  - stage: Deploy_Keycloak
    dependsOn: Deploy_Microservices
    jobs:
      - job: Deploy_Keycloak
        steps:
          - checkout: self  # Necesario si usa plantillas dentro del mismo repo
          - template: keycloak/azure-pipelines.yml  # Ahora este archivo es solo 'steps'

  - stage: Deploy_APIM
    dependsOn: Deploy_Keycloak
    jobs:
      - job: Deploy_APIM
        steps:
          - checkout: self  # Permite acceder a la plantilla dentro del repo
          - template: apim/azure-pipelines.yml  # Ahora este archivo es solo 'steps'