trigger: none  # Se ejecuta manualmente o programado

stages:
  - stage: Deploy_Microservices
    jobs:
      - job: Trigger_Microservices
        steps:
          - checkout: none
          - task: AzurePipelinesRunPipeline@1
            displayName: "Ejecutar Pipeline de Microservicios"
            inputs:
              definition: "deploy-microservices"
              parameters: "{}"

  - stage: Deploy_Keycloak
    dependsOn: Deploy_Microservices
    jobs:
      - job: Trigger_Keycloak
        steps:
          - checkout: none
          - template: keycloak/azure-pipelines.yml

  - stage: Deploy_APIM
    dependsOn: Deploy_Keycloak
    jobs:
      - job: Trigger_APIM
        steps:
          - checkout: none
          - template: apim/azure-pipelines.yml
