steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "Deploy APIM"
    inputs:
      azureSubscription: "AzureServiceConnection"
      resourceGroupName: "api-manager-rg"
      location: "East US"
      templateLocation: "Linked artifact"
      csmFile: "apim/apim-template.json"
